#!/bin/sh
#
# Copyright (C) 2014 Brian Murphy <brian@murphy.dk>
#
# This file is part of git_filter, distributed under the GNU GPL v2.
# For full terms see the included COPYING file.
#

syntax()
{
    echo "syntax: $0 CONFIGFILE"
    exit 1
}

if [ "set${1}" == "set" ]; then
    syntax
fi

CONFIG_FILE=$1

ROOT=`dirname $0`

echo $ROOT
if [ "set${ROOT}" != "set" ]; then
    ROOT=${ROOT}/
fi

REPO=`awk '/^REPO: / {print $2}' $CONFIG_FILE |head -n 1`

NAMES=`awk '/^FILT: / {print $2}' $CONFIG_FILE`

TPFX=`awk '/^TPFX: / {print $2}' $CONFIG_FILE`

for name in $NAMES; do
    ${ROOT}clean_git $REPO $TPFX$name
done
