#!/bin/sh
#
# Copyright (C) 2014 Brian Murphy <brian@murphy.dk>
#
# This file is part of git_filter, distributed under the GNU GPL v2.
# For full terms see the included COPYING file.
#

syntax()
{
    echo "syntax: $0 CONFIGFILE [init]"
    exit 1
}

if [ "set${1}" == "set" ]; then
    syntax
fi

CONFIG_FILE=$1

REPO=`awk '/^REPO: / {print $2}' $CONFIG_FILE |head -n 1`
NAMES=`awk '/^FILT: / {print $2}' $CONFIG_FILE`
TPFX=`awk '/^TPFX: / {print $2}' $CONFIG_FILE`

REPO_GIT=$REPO/.git

# repack the source repository to ensure it is compact
# speeds up the push later
git --git-dir=$REPO_GIT repack -ad

for name in $NAMES; do
    newrepo=$TPFX$name
    if [ "set${2}" == "setinit" ]; then
        git --git-dir=$newrepo init
    fi
    git --git-dir=$REPO_GIT push $newrepo $newrepo:master
done
